config_url = r'https://emille-master-ui-internal.digital.fcalatam.com.br/Configuration'
chrome_path = r'dependencies/chromedriver.exe'
login_url = r'https://emille-master-ui-internal.digital.fcalatam.com.br/Login'
excel_path = r'recover_data.xlsx'
file_name = r'dependencies/authentication.txt'