config_url = r'https://emille-master-ui-internal.digital.fcalatam.com.br/Configuration'
chrome_path = r'dependencies/chromedriver.exe'
login_url = r'https://emille-master-ui-internal.digital.fcalatam.com.br/Login'
creat_url = r'https://emille-master-ui-internal.digital.fcalatam.com.br/ConfigurationCreate'
excel_backup_path = r'recover_cycle_time_data.xlsx'
file_name = r'dependencies/authentication.txt'
excel_add_ct_path = r'add_cycle_time.xlsx'